### ISSUE TITLE
[ERROR] ENOENT: no such file or directory, open 'node_modules/handlebars/dist/handlebars.runtime.min.js'"

### ISSUE THREAD

**Issue by DerTobi75** [droppyjs/droppy#56]
Sorry, I am new to Nodejs & npm and I do not know, if it is an Issue or Bug or just me ;-)

When I try to start droppy I get the following Error " [ERROR] ENOENT: no such file or directory, open 'node_modules/handlebars/dist/handlebars.runtime.min.js'".

Ubuntu 20.04.4 LTS
npm --version: 6.14.16
node --version: v12.22.10

```bash
tobias@hpserver:~$ sudo droppy start
[sudo] password for tobias: 

           .:.
    :::  .:::::.   @droppyjs/server 0.2.3 running on node 12.22.10
  ..:::..  :::     config at /root/.droppy/config
   ':::'   :::     files at /root/.droppy/files
     '

2022-03-13 16:45:41 [INFO] Configuration: { listeners: [ { host: [ '0.0.0.0', '::' ], port: 8989, protocol: 'http' } ], public: false, timestamps: true, linkLength: 5, linkExtensions: false, logLevel: 2, maxFileSize: 0, updateInterval: 1000, pollingInterval: 0, keepAlive: 20000, uploadTimeout: 604800000, allowFrame: false, readOnly: false, ignorePatterns: [], watch: true, headers: {}}
2022-03-13 16:45:41 [INFO] Loading resources ...
2022-03-13 16:45:41 [INFO] ENOENT /root/.droppy/cache/cache.json, building cache ...
2022-03-13 16:45:41 [ERROR] ENOENT: no such file or directory, open 'node_modules/handlebars/dist/handlebars.runtime.min.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at /usr/lib/node_modules/@droppyjs/cli/node_modules/@droppyjs/server/lib/services/resources.js:423:19
    at Array.forEach (<anonymous>)
    at Object.resources.compileJS (/usr/lib/node_modules/@droppyjs/cli/node_modules/@droppyjs/server/lib/services/resources.js:419:22)
    at compileAll (/usr/lib/node_modules/@droppyjs/cli/node_modules/@droppyjs/server/lib/services/resources.js:477:38)
    at compile (/usr/lib/node_modules/@droppyjs/cli/node_modules/@droppyjs/server/lib/services/resources.js:269:21)
    at ReadFileContext.callback (/usr/lib/node_modules/@droppyjs/cli/node_modules/@droppyjs/server/lib/services/resources.js:181:14)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13)```

**Comment by markhughes** [comment]
Resolved, please update to the latest version. :)
