### ISSUE TITLE
Docker Install

### ISSUE THREAD

**Issue by Northwave** [droppyjs/droppy#99]
Hi, when will be the Docker install available again ?

**Comment by markhughes** [comment]
What issue do you have?

**Comment by Northwave** [comment]
I cant find the current docker container, also the manual here mentions that its currently broken

Edit: seems like the manual was updated

**Comment by markhughes** [comment]
Hey, sorry about that. The README was outdated. I have updated it now

There is a sample composer file here: https://github.com/droppyjs/droppy/blob/canary/examples/docker-compose.yml

You can use FROM ghcr.io/droppyjs/droppy to grab the image.

Hope that helps

**Comment by glats** [comment]
I tried to use the image but i got this error which was resolved here i think: https://github.com/droppyjs/droppy/pull/96/files
```
          .:.
    :::  .:::::.   @droppyjs/server 1.0.1 running on node 20.16.0
  ..:::..  :::     config at /config
   ':::'   :::     files at /files
     '

2024-08-16 00:00:41 [INFO] Configuration: { listeners: [ { host: [ '0.0.0.0', '::' ], port: 8989, protocol: 'http' } ], public: false, timestamps: true, linkLength: 5, linkExtensions: false, logLevel: 2, maxFileSize: 0, updateInterval: 1000, pollingInterval: 0, keepAlive: 20000, uploadTimeout: 604800000, allowFrame: false, readOnly: false, ignorePatterns: [], watch: true, headers: {}}
2024-08-16 00:00:41 [INFO] Loading resources ...
2024-08-16 00:00:41 [INFO] ENOENT /home/droppy/.droppy/cache/cache.json, building cache ...
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
2024-08-16 00:00:47 [ERROR] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at Object.join (node:path:1175:7)
    at /droppy/packages/server/lib/services/svg.js:16:72
    at Array.forEach (<anonymous>)
    at svg (/droppy/packages/server/lib/services/svg.js:15:35)
    at resources.compileHTML (/droppy/packages/server/lib/services/resources.js:462:43)
    at compileAll (/droppy/packages/server/lib/services/resources.js:483:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async compile (/droppy/packages/server/lib/services/resources.js:273:15)
```

**Comment by markhughes** [comment]
Hey @j1cs can you share your docker image?

**Comment by glats** [comment]
i'm sorry i was referring to ghcr.io/droppyjs/droppy image

**Comment by markhughes** [comment]
@j1cs are you using docker compose file?

How are you starting it?

**Comment by glats** [comment]
like this:
```
  droppy:
    image: ghcr.io/droppyjs/droppy
    ports:
      - '9002:8989'
    volumes:
      - '/media/stuff/droppy:/files'
      - './droppy/config:/config'
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - web-network
```
finally `docker compose up`

**Comment by markhughes** [comment]
In all honestly, the Dockerfile we publish needs to be redone! 

I'm guessing this is a permissions issue with the files.

Inside your local config directory do you have any files showing?

**Comment by Northwave** [comment]
if this helps, my log looks like this. sorry i forgot to answer back then...

I run it on unraid, if thats important:

Config:

Name: DroppyJs

Additional Requirements: None Listed
Repository: ghcr.io/droppyjs/droppy
Network Type: Bridge
Console shell command: Shell
Privileged: Off
Port: 8989  Container Port: 8989

Appdata:
/mnt/user/appdata/droppy-new
Container Path: /config

Files:
/mnt/user/Files/Droppy-Share/
Container Path: /files

2024-08-18 22:12:44 [INFO] Configuration: { listeners: [ { host: [ '0.0.0.0', '::' ], port: 8989, protocol: 'http' } ], public: false, timestamps: true, linkLength: 5, linkExtensions: false, logLevel: 2, maxFileSize: 0, updateInterval: 1000, pollingInterval: 0, keepAlive: 20000, uploadTimeout: 604800000, allowFrame: false, readOnly: false, ignorePatterns: [], watch: true, headers: {}}
2024-08-18 22:12:44 [INFO] Loading resources ...
2024-08-18 22:12:44 [INFO] ENOENT /home/droppy/.droppy/cache/cache.json, building cache ...
2024-08-18 22:12:45 [ERROR] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at Object.join (node:path:1175:7)
    at /droppy/packages/server/lib/services/svg.js:16:72
    at Array.forEach (<anonymous>)
    at svg (/droppy/packages/server/lib/services/svg.js:15:35)
    at resources.compileHTML (/droppy/packages/server/lib/services/resources.js:462:43)
    at compileAll (/droppy/packages/server/lib/services/resources.js:483:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async compile (/droppy/packages/server/lib/services/resources.js:273:15)

**Comment by glats** [comment]
> In all honestly, the Dockerfile we publish to be redone!
> 
> I'm guessing this is a permissions issue with the files.
> 
> Inside your local config directory do you have any files showing?

i tried without the volumes mounted and occurs the same problem.

**Comment by voteforpresident** [comment]
Is there any solution to this?

[ERROR] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at Object.join (node:path:1244:7)
    at /droppy/packages/server/lib/services/svg.js:16:72
    at Array.forEach (<anonymous>)
    at svg (/droppy/packages/server/lib/services/svg.js:15:35)
    at resources.compileHTML (/droppy/packages/server/lib/services/resources.js:462:43)
    at compileAll (/droppy/packages/server/lib/services/resources.js:483:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async compile (/droppy/packages/server/lib/services/resources.js:273:15)

**Comment by Northwave** [comment]
Will this be fixed anytime soon ? Im still on the deprecated old version :(

**Comment by markhughes** [comment]
Apologies I've been caught up. I'm just on my work break, but I'll take a look tonight and get something up

**Comment by Northwave** [comment]
Hi ! Thx it should be fixed now. I just had to use the tag :4285744b instead of latest. Maybe you should switch latest to a newer build ?
